//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productID { get; set; }
        public Nullable<int> productcategoryID { get; set; }
        public string productName { get; set; }
        public Nullable<double> productPrice { get; set; }
        public Nullable<int> productInventory { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
