//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int claimID { get; set; }
        public Nullable<int> memberID { get; set; }
        public Nullable<int> receiptID { get; set; }
        public string claimPname { get; set; }
        public string claimDetails { get; set; }
        public Nullable<System.DateTime> claimDate { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
