//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int expensesID { get; set; }
        public Nullable<int> purchaseorderID { get; set; }
        public string expensesName { get; set; }
        public Nullable<double> expensesTotalprice { get; set; }
        public Nullable<System.DateTime> expensesDate { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
