//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Incomes = new HashSet<Income>();
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int invoiceID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> memberID { get; set; }
        public string invoicePname { get; set; }
        public Nullable<int> invoiceQTY { get; set; }
        public Nullable<double> invoicePrice { get; set; }
        public Nullable<double> invoiceTotalPrice { get; set; }
        public Nullable<System.DateTime> invoiceDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Income> Incomes { get; set; }
        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
