//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Claims = new HashSet<Claim>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int memberID { get; set; }
        public string memberFname { get; set; }
        public string memberLname { get; set; }
        public Nullable<int> memberPhone { get; set; }
        public string memberNohouse { get; set; }
        public string memberRoad { get; set; }
        public string memberDistrict { get; set; }
        public string memberSubdistrict { get; set; }
        public string memberProvince { get; set; }
        public Nullable<int> memberPost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
