//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequisition
    {
        public int purchaserequisitionID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<int> productID { get; set; }
        public string purchaserequisitionName { get; set; }
        public Nullable<int> PurchaserequisitionQTY { get; set; }
        public Nullable<double> purchaserequisitionPrice { get; set; }
        public Nullable<System.DateTime> purchaserequisitionDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
