//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.Claims = new HashSet<Claim>();
        }
    
        public int receiptID { get; set; }
        public Nullable<int> invoiceID { get; set; }
        public string receiptPname { get; set; }
        public Nullable<int> receiptQTY { get; set; }
        public Nullable<double> receiptPrice { get; set; }
        public Nullable<double> receiptTotalPrice { get; set; }
        public Nullable<System.DateTime> receiptDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
